In [2]:
import numpy as np


# Exercise 1: Import NumPy and print its version

In [3]:
print(np.__version__)

2.2.0


# Exercise 2: Create a null vector of size 10

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Exercise 3: Create a vector with values ranging from 10 to 49

In [5]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Exercise 4: Reverse a vector (first element becomes last)

In [6]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# Exercise 5: Create a 3x3 matrix with values from 0 to 8

In [7]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Exercise 6: Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)
print(nonzero_indices)

(array([0, 1, 4]),)


# Exercise 7: Create a 3x3 identity matrix

In [9]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Exercise 8: Create a 3x3x3 array with random values

In [10]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.91751907 0.47034364 0.05005366]
  [0.88570494 0.64853634 0.39208459]
  [0.69889814 0.18470307 0.58905308]]

 [[0.04965567 0.27385895 0.29927968]
  [0.08991245 0.42612945 0.9593989 ]
  [0.51009174 0.78956768 0.04577655]]

 [[0.78740679 0.9244333  0.49782101]
  [0.11838449 0.00914051 0.78057365]
  [0.42452021 0.13960268 0.67775129]]]


# Exercise 9: Create a 10x10 array with random values and find the minimum and maximum

In [11]:
rnd_array = np.random.random((10, 10))
print(rnd_array)
print("Min value:", rnd_array.min())
print("Max value:", rnd_array.max())

[[0.1946157  0.15863975 0.81079354 0.97509533 0.24559814 0.97038049
  0.78353199 0.95390798 0.27935245 0.49718587]
 [0.20950287 0.22090428 0.61572685 0.0930418  0.32327867 0.1357213
  0.66782033 0.93828883 0.47048115 0.54241121]
 [0.96862197 0.92859236 0.68472182 0.36573324 0.73955207 0.71581812
  0.56608692 0.44584677 0.58212302 0.18718554]
 [0.10215807 0.61816358 0.64014484 0.92471921 0.66306291 0.00655284
  0.67879333 0.70482153 0.34652927 0.90817648]
 [0.39911438 0.49946016 0.88611388 0.61249807 0.00634171 0.95136952
  0.01076914 0.36732602 0.40226947 0.61166795]
 [0.73314815 0.22561454 0.03850046 0.57062664 0.76948915 0.99498376
  0.75766729 0.92044921 0.79237255 0.55472888]
 [0.73702526 0.86773307 0.71639456 0.48385736 0.1305796  0.83605132
  0.86992671 0.27733424 0.60666903 0.09425184]
 [0.2311687  0.43435602 0.02391343 0.06136978 0.4976771  0.44880227
  0.42312898 0.52798134 0.18717878 0.08286272]
 [0.33897982 0.22515417 0.88808334 0.35123723 0.57823599 0.12065247
  0.97571592 

# Exercise 10: Create a random vector of size 30 and find the mean value

In [12]:
random_vector = np.random.random(30)
print(random_vector)
print("Mean value:", random_vector.mean())

[0.58519212 0.14263181 0.70769538 0.31011426 0.64144517 0.84596359
 0.62527194 0.20039158 0.16906153 0.7125734  0.6899058  0.97813901
 0.01128651 0.12116198 0.19335663 0.84368076 0.75979659 0.59279631
 0.49673563 0.56504964 0.3709044  0.89423245 0.69984675 0.67631808
 0.86490548 0.29258869 0.51231796 0.13986349 0.95413893 0.48522577]
Mean value: 0.5360863873503707


# Exercise 11: Create a 5x5 matrix with row values ranging from 0 to 4

In [13]:
matrix_5x5 = np.tile(np.arange(5), (5, 1))
print(matrix_5x5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


 # Exercise 12: Create a checkerboard pattern (8x8 matrix)

In [14]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Exercise 13: Create a 3x3x3 array with random values

In [15]:
random_array_3x3x3 = np.random.random((3, 3, 3))
print(random_array_3x3x3)

[[[0.62103435 0.23954616 0.88102554]
  [0.22737173 0.11476938 0.78744054]
  [0.89132617 0.18723801 0.25131726]]

 [[0.59248825 0.13524828 0.96353296]
  [0.23478346 0.51673404 0.29037111]
  [0.01693243 0.39179235 0.94672087]]

 [[0.13055728 0.67250525 0.03534804]
  [0.77138188 0.30279559 0.79772665]
  [0.01838767 0.30637724 0.80609452]]]


# Exercise 14: Create a 10x10 array with random values and find the min and max

In [16]:
rand_10x10 = np.random.random((10, 10))
print("Min:", rand_10x10.min(), "Max:", rand_10x10.max())

Min: 0.00815565342313862 Max: 0.9988904436454114


# Exercise 15: Create a random vector of size 30 and find the mean value

In [17]:
random_vector_30 = np.random.random(30)
print("Mean value:", random_vector_30.mean())

Mean value: 0.5215954078455548


# Exercise 16: Create a 2D array with 1 on the border and 0 inside

In [18]:
border_matrix = np.ones((5, 5))
border_matrix[1:-1, 1:-1] = 0
print(border_matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Exercise 17: Add a border (filled with 0s) around an existing array

In [19]:
original_matrix = np.ones((3, 3))
bordered_matrix = np.pad(original_matrix, pad_width=1, mode='constant', constant_values=0)
print(bordered_matrix)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# Exercise 18: Results of expressions

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


# Exercise 19: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [24]:
diag_matrix = np.diag(np.arange(1, 5), k=-1)
print(diag_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Exercise 20: Create an 8x8 matrix and fill it with a checkerboard pattern

In [21]:
checkerboard_8x8 = np.zeros((8, 8), dtype=int)
checkerboard_8x8[1::2, ::2] = 1
checkerboard_8x8[::2, 1::2] = 1
print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Exercise 21: Create a checkerboard 8x8 matrix using the tile function

In [22]:
checkerboard_tile = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Exercise 22: Normalize a 5x5 random matrix

In [23]:
random_matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (random_matrix_5x5 - random_matrix_5x5.min()) / (random_matrix_5x5.max() - random_matrix_5x5.min())
print(normalized_matrix)

[[0.61070583 0.96503554 0.22859007 0.66661546 1.        ]
 [0.         0.10582126 0.3457638  0.48334943 0.58717335]
 [0.42465312 0.62404904 0.90396328 0.84882136 0.06268456]
 [0.3906223  0.78826143 0.80601304 0.64057787 0.81217232]
 [0.81705957 0.25147013 0.56243462 0.41454199 0.27311899]]


# Exercise 23: Create a custom dtype describing a color as four unsigned bytes (RGBA)

In [24]:
color_dtype = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
print(color_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


# Exercise 24: Multiply a 5x3 matrix by a 3x2 matrix

In [25]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
result = np.dot(A, B)
print(result)

[[0.27522562 1.07919441]
 [0.44132838 0.89738564]
 [0.38855883 1.03786687]
 [0.58985362 1.18987238]
 [0.56311642 1.270207  ]]


# Exercise 25: Negate all elements in a vector between 3 and 8

In [26]:
Z = np.arange(10)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


# Exercise 26: Output of the given script

In [27]:
print(sum(range(5), -1))
print(sum(range(5), -1))

9
9


# Exercise 27: Which expressions are legal

In [28]:
Z = np.arange(10)
try:
    print(Z**Z)
    print(2 << Z >> 2)
    print(Z <- Z)
    print(1j*Z)
    print(Z/1/1)
    print(Z<Z>Z)  
except Exception as e:
    print("Error:", e)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [29]:
# Exercise 28: Results of expressions
import warnings
warnings.filterwarnings("ignore")
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


# Exercise 29: Round away from zero a float array

In [30]:
Z = np.random.uniform(-10, 10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-9. 10. -2. -8. -4.  6. -4.  1. -1. -6.]


# Exercise 30: Find common values between two arrays

In [31]:
A = np.random.randint(0, 10, 10)
B = np.random.randint(0, 10, 10)
print(np.intersect1d(A, B))

[1 4 5 9]


# Exercise 31: Ignore all numpy warnings

In [32]:
import warnings
warnings.filterwarnings("ignore")
print("Warnings ignored")

Warnings ignored


In [33]:
#### 32. Is the following expressions true? 
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

# Exercise 33: Get yesterday, today, tomorrow

In [34]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2025-03-07 2025-03-08 2025-03-09


# Exercise 34: Get all dates of July 2016

In [35]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [36]:
A = np.ones(3)
B = np.ones(3)*2
np.add(A, B, out=A)
np.divide(A, -2, out=A)
print(A)

[-1.5 -1.5 -1.5]


# 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [37]:
Z = np.random.uniform(0, 10, 10)
print(Z.astype(int))
print(np.floor(Z))
print(np.ceil(Z)-1)
print(np.trunc(Z))

[1 8 2 6 0 7 8 0 8 4]
[1. 8. 2. 6. 0. 7. 8. 0. 8. 4.]
[1. 8. 2. 6. 0. 7. 8. 0. 8. 4.]
[1. 8. 2. 6. 0. 7. 8. 0. 8. 4.]


# 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [38]:
matrix_5x5 = np.tile(np.arange(5), (5, 1))
print(matrix_5x5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Exercise 38: Generate 10 integers using a generator function and build an array

In [39]:
def generate():
    for i in range(10):
        yield i
Z = np.fromiter(generate(), dtype=int)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


# Exercise 39: Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [40]:
Z = np.linspace(0, 1, 12, endpoint=False)[1:-1]
print(Z)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


# Exercise 40: Create a random vector of size 10 and sort it

In [41]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.27533209 0.29160725 0.32185952 0.33704297 0.39846842 0.44338282
 0.52638452 0.55391612 0.72003519 0.94578104]


# Exercise 41: Sum a small array faster than np.sum

In [42]:
Z = np.arange(10)
print(np.add.reduce(Z))

45


# Exercise 42: Check if two random arrays are equal

In [43]:
A = np.random.randint(0, 2, 10)
B = np.random.randint(0, 2, 10)
print(np.array_equal(A, B))

False


# Exercise 43: Make an array immutable

In [44]:
Z = np.zeros(10)
Z.flags.writeable = False
print("Immutable array created")

Immutable array created


# Exercise 44: Convert Cartesian coordinates to polar

In [45]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
Theta = np.arctan2(Y, X)
print(R, Theta)

[0.71270165 0.14937203 0.48229551 0.49666488 0.90758331 0.57990647
 0.9250776  0.75692106 0.5884442  1.01614436] [1.20772169 0.38824538 0.58512994 1.35467689 0.79234649 0.59538597
 0.00873384 0.85650292 1.18553281 0.68085117]


# Exercise 45: Replace max value in vector with 0

In [46]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.19226951 0.68248789 0.12682905 0.51779636 0.57322529 0.36727356
 0.12806197 0.10471863 0.         0.28700111]


# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [47]:
Z = np.zeros((5, 5), dtype=[("x", float), ("y", float)])
Z["x"], Z["y"] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 

In [48]:
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222 -0.18181818 -0.15384615]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.         -0.66666667 -0.4       ]
 [ 0.13333333  0.153846

# 48. Print the minimum and maximum representable value for each numpy scalar type

In [49]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min, np.finfo(dtype).max)

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


# 49. How to print all the values of an array? 

In [50]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((10, 10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 50. How to find the closest value (to a given scalar) in a vector?

In [51]:
Z = np.random.random(10)
scalar = 0.5
print(Z[np.abs(Z - scalar).argmin()])

0.41725337287709996


# 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [52]:
dtype = [('position', float, 2), ('color', float, 3)]
arr = np.zeros(5, dtype=dtype)
print(arr)

[([0., 0.], [0., 0., 0.]) ([0., 0.], [0., 0., 0.])
 ([0., 0.], [0., 0., 0.]) ([0., 0.], [0., 0., 0.])
 ([0., 0.], [0., 0., 0.])]


# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [53]:
coords = np.random.rand(100, 2)
distances = np.sqrt(((coords[:, np.newaxis] - coords) ** 2).sum(axis=2))
print(distances)

[[0.         0.54950392 0.4180527  0.22249312 0.36888231 0.69759692
  0.50404526 0.41648654 0.8653464  0.57341748 0.34225517 0.59928032
  0.11324191 0.5338469  0.80598796 0.6395184  0.89585998 0.32749297
  0.93183919 0.74287504 0.60075171 0.60815342 0.86410611 0.20061182
  0.86126057 0.19948225 0.70323486 0.68696822 0.29374794 0.38944904
  0.63827935 0.45123282 0.14182696 0.22445669 0.0937968  0.67904757
  0.25361599 0.11666361 0.52424227 0.45598491 0.13733938 0.49719509
  0.60702974 0.22706813 0.28626098 0.48352808 0.78702345 0.98034833
  0.46011468 0.62178365 0.69735856 0.5311071  0.24739728 0.79286591
  0.46230798 0.97141455 0.45342783 0.71964213 0.59655505 0.29192734
  0.91951068 0.08908768 0.70919803 0.65393101 0.20176466 0.25623531
  0.60468547 0.83253314 0.0519154  0.76337291 0.96922545 0.10107207
  0.46109315 1.04045962 0.81350331 0.70093338 0.03496907 0.61735622
  0.23510957 0.2515905  0.10945069 0.60692144 0.49609297 0.22640346
  0.50074389 0.29782362 0.53579011 0.40601174 0.

# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
float_arr = np.arange(10, dtype=np.float32)
float_arr = float_arr.astype(np.int32, copy=False)
print(float_arr)

[0 1 2 3 4 5 6 7 8 9]


# 54. How to read the following file? 
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [55]:
from io import StringIO
text = """1, 2, 3, 4, 5\n6,  ,  , 7, 8\n ,  , 9,10,11"""
file = StringIO(text)
data = np.genfromtxt(file, delimiter=",", dtype=int)
print(data)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


# 55. What is the equivalent of enumerate for numpy arrays?

In [56]:
arr = np.array([10, 20, 30, 40])
for index, value in np.ndenumerate(arr):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40


# 56. Generate a generic 2D Gaussian-like array

In [57]:
def gaussian(size, sigma=1.0):
    x, y = np.meshgrid(np.linspace(-1, 1, size), np.linspace(-1, 1, size))
    g = np.exp(-(x**2 + y**2) / (2 * sigma**2))
    return g / g.sum()
print(gaussian(5))

[[0.02324684 0.03382395 0.03832756 0.03382395 0.02324684]
 [0.03382395 0.04921356 0.05576627 0.04921356 0.03382395]
 [0.03832756 0.05576627 0.06319146 0.05576627 0.03832756]
 [0.03382395 0.04921356 0.05576627 0.04921356 0.03382395]
 [0.02324684 0.03382395 0.03832756 0.03382395 0.02324684]]


# 57. How to randomly place p elements in a 2D array?

In [58]:
n, p = 10, 5
arr = np.zeros((n, n))
coords = np.random.choice(n*n, p, replace=False)
arr[np.unravel_index(coords, (n, n))] = 1
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]


# 58. Subtract the mean of each row of a matrix

In [59]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.11105126 -0.03971477  0.05491626  0.12363217 -0.13059613 -0.06707418
  -0.19615832  0.53867792 -0.23174764  0.05911596]
 [-0.06758113 -0.05486922  0.20739053 -0.45825449  0.34966876 -0.13000629
   0.12248928 -0.10669682  0.32091575 -0.18305637]
 [-0.15733177  0.25129966 -0.07345827  0.3839966  -0.15730981  0.05634866
  -0.4187185   0.16586606 -0.41640015  0.3657075 ]
 [-0.24227717 -0.13524859 -0.08416065  0.36386755 -0.28068279 -0.08176484
  -0.14428119  0.09182731  0.37861755  0.13410281]
 [ 0.18542531 -0.00560578  0.14579658  0.27823426 -0.10482992  0.13462725
  -0.4951645  -0.20169289 -0.06820539  0.13141507]]


# 59. How to sort an array by the nth column?

In [60]:
arr = np.random.randint(0, 100, (5, 5))
n = 2
arr = arr[arr[:, n].argsort()]
print(arr)

[[33 35 10  4 43]
 [35 90 49 77 75]
 [51 71 86 83 40]
 [69 55 88 55 88]
 [84 57 99 44 79]]


# 60. How to tell if a given 2D array has null columns?

In [61]:
Z = np.random.randint(0, 2, (5, 5))
print((Z.sum(axis=0) == 0).any())

False


# 61. Find the nearest value from a given value in an array

In [62]:
arr = np.random.rand(10)
val = 0.5
nearest = arr[np.abs(arr - val).argmin()]
print(nearest)

0.5977851907231141


# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [31]:

A = np.array([[1, 2, 3]])  
B = np.array([[4], [5], [6]])
C = np.empty((3, 3))
with np.nditer([A, B, C], op_flags=[['readonly'], ['readonly'], ['writeonly']], flags=['external_loop', 'buffered']) as it:
    for a, b, c in it:
        c[...] = a + b  
print(C)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


# 63. Create an array class that has a name attribute

In [64]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
A = NamedArray(np.arange(10), "Test Array")
print(A.name)

Test Array


# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [65]:
Z = np.zeros(10)
I = np.random.randint(0, 10, 20)
np.add.at(Z, I, 1)
print(Z)

[1. 3. 3. 3. 1. 3. 2. 2. 2. 0.]


# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [66]:
X = np.arange(10)
I = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
F = np.zeros(10)
np.add.at(F, I, X)
print(F)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [67]:
w, h = 64, 64
I = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)
unique_colors = len(np.unique(I.reshape(-1, 3), axis=0))
print(unique_colors)

4096


# 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [68]:
A = np.random.rand(3, 4, 3, 3)
result = A.sum(axis=(-2, -1))
print(result)

[[5.47104925 3.67388929 3.89475203 4.97258809]
 [5.17148221 3.0744229  5.78111327 4.77110612]
 [3.65925807 3.27582478 3.29238946 4.16624758]]


# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? 

In [69]:
def subgroup_means(D, S):
    return np.array([D[S == i].mean() for i in np.unique(S)])
D = np.random.rand(100)
S = np.random.randint(0, 10, 100)
print(subgroup_means(D, S))

[0.57002762 0.38856462 0.483216   0.54979366 0.47990969 0.45102479
 0.65467093 0.52970202 0.43359199 0.50148213]


# 69. How to get the diagonal of a dot product?

In [70]:
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)
diagonal = np.einsum("ii->i", np.dot(A, B))
print(diagonal)

[2.02592995 2.21266361 1.40583235 0.71977412 0.88481436]


# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [71]:
Z = np.array([1, 2, 3, 4, 5])
R = np.zeros(len(Z) + (len(Z)-1)*3)
R[::4] = Z
print(R)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [72]:
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5, 1)
print(A * B)

[[[0.59218015 0.16243814 0.57109562]
  [0.07512895 0.01960736 0.07257097]
  [0.03268223 0.01569599 0.05546293]
  [0.00817587 0.00915747 0.03326768]
  [0.75833482 0.01252015 0.59498455]]

 [[0.05254007 0.08968696 0.05378995]
  [0.2061222  0.426151   0.07267099]
  [0.36847072 0.53527203 0.05303987]
  [0.55066287 0.42325668 0.18771853]
  [0.42752856 0.02724799 0.00544121]]

 [[0.05500831 0.1457902  0.12475382]
  [0.09028355 0.10097826 0.09541831]
  [0.77552895 0.50884709 0.36579629]
  [0.7089492  0.3517559  0.07827435]
  [0.42694401 0.243712   0.09391774]]

 [[0.21893944 0.46238832 0.50814464]
  [0.59997579 0.05765831 0.74499166]
  [0.6009898  0.85150666 0.54127329]
  [0.03067106 0.26389598 0.16016042]
  [0.18375788 0.22856076 0.3146545 ]]

 [[0.04811274 0.01654198 0.15093343]
  [0.06406358 0.00435899 0.05463012]
  [0.0334454  0.0294811  0.03257329]
  [0.2109455  0.00883927 0.23495246]
  [0.01464132 0.06254301 0.02883028]]]


# 72. How to swap two rows of an array?

In [73]:
Z = np.arange(25).reshape(5, 5)
Z[[0, 1]] = Z[[1, 0]]
print(Z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 

In [74]:
triangles = np.random.randint(0, 10, (10, 3))
edges = np.vstack([triangles[:, [0, 1]], triangles[:, [1, 2]], triangles[:, [2, 0]]])
edges = np.sort(edges, axis=1)
unique_edges = np.unique(edges, axis=0)
print(unique_edges)

[[0 1]
 [0 2]
 [0 3]
 [0 7]
 [0 8]
 [0 9]
 [1 3]
 [1 8]
 [1 9]
 [2 7]
 [3 7]
 [3 8]
 [3 9]
 [7 8]
 [7 9]
 [8 8]
 [9 9]]


# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [75]:
C = np.array([0, 3, 1, 2, 0, 1])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 1 2 3 3 5]


# 75. How to compute averages using a sliding window over an array?

In [76]:
def moving_average(a, n=3):
    return np.convolve(a, np.ones(n)/n, mode='valid')

Z = np.arange(10)
print(moving_average(Z, 3))

[1. 2. 3. 4. 5. 6. 7. 8.]


# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [77]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, window_shape=4)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# 77. How to negate a boolean, or to change the sign of a float inplace?

In [78]:
Z = np.array([True, False, True])
Z = ~Z
print(Z)

Z = np.array([1.0, -2.0, 3.0])
Z *= -1
print(Z)

[False  True False]
[-1.  2. -3.]


# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [79]:
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [1, 2], [3, 3]])  
p = np.array([1, 1])


# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [93]:
P = np.random.rand(5, 2)
distances = np.abs(np.cross(P1[:, None] - P0[:, None], P0[:, None] - P[None, :])) / np.linalg.norm(P1[:, None] - P0[:, None], axis=2)
print("Distances from each point to each line:", distances)

Distances from each point to each line: [[0.82708853 0.66076782 0.31410775 0.07048824 0.68966745]
 [0.85840165 0.74199494 0.25832686 0.93205314 0.15840016]
 [0.48471476 0.28479628 0.30233439 0.00179703 0.10743242]]


# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [94]:
def extract_subpart(Z, center, shape, fill=0):
    R = np.ones(shape) * fill
    start = np.array(center) - np.array(shape) // 2
    end = start + shape
    slices = tuple(slice(max(s, 0), min(e, Z.shape[i])) for i, (s, e) in enumerate(zip(start, end)))
    R_slices = tuple(slice(max(-s, 0), min(Z.shape[i] - s, shape[i])) for i, s in enumerate(start))
    R[R_slices] = Z[slices]
    return R

# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [95]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, 4)
print("81. Sliding Windows:\n", R)

81. Sliding Windows:
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# 82. Compute a matrix rank

In [96]:
matrix = np.random.randint(0, 10, (5, 5))
rank = np.linalg.matrix_rank(matrix)
print(" Matrix Rank:\n", rank)

 Matrix Rank:
 5


# 83. How to find the most frequent value in an array?

In [97]:
arr = np.random.randint(0, 10, 20)
most_frequent = np.bincount(arr).argmax()
print(" Most Frequent Value:\n", most_frequent)

 Most Frequent Value:
 9


# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [98]:
random_matrix = np.random.randint(0, 10, (10, 10))
blocks = np.lib.stride_tricks.sliding_window_view(random_matrix, (3, 3))
print(" 3x3 Blocks Shape:\n", blocks.shape)

 3x3 Blocks Shape:
 (8, 8, 3, 3)


# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [99]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

def symmetric_array(shape):
    obj = np.zeros(shape).view(SymmetricArray)
    return obj

Z = symmetric_array((5, 5))
Z[2, 3] = 7
print(" Symmetric Array:\n", Z)

 Symmetric Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 

In [100]:
p, n = 3, 4
matrices = np.random.randint(0, 10, (p, n, n))
vectors = np.random.randint(0, 10, (p, n, 1))
result = np.sum(np.matmul(matrices, vectors), axis=0)
print(" Sum of Matrix Products:\n", result)

 Sum of Matrix Products:
 [[237]
 [183]
 [231]
 [301]]


# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [101]:
A = np.random.rand(16, 16)
k = 4
block_sum_result = np.add.reduceat(np.add.reduceat(A, np.arange(0, A.shape[0], k), axis=0), np.arange(0, A.shape[1], k), axis=1)
print("Block-Sum Result:\n", block_sum_result)


Block-Sum Result:
 [[ 6.98817651  8.19296246  7.770081    6.69854123]
 [ 8.42857655  8.8000523   7.69905301  7.35910457]
 [ 8.31517672  7.23366744  8.79453714 10.25894403]
 [ 6.6673222   8.64332126  6.87032462  9.69441951]]


# 88. How to implement the Game of Life using numpy arrays?

In [102]:
Z = np.random.randint(0, 2, (10, 10))
neighbors = sum(np.roll(np.roll(Z, i, 0), j, 1) for i in (-1, 0, 1) for j in (-1, 0, 1) if (i != 0 or j != 0))
game_of_life_result = (neighbors == 3) | (Z & (neighbors == 2))
print("Game of Life Next Step:\n", game_of_life_result)

Game of Life Next Step:
 [[0 0 0 0 0 1 0 1 0 0]
 [1 0 1 1 0 1 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 1 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 1 0 0 0 1 0]
 [1 1 1 1 0 0 0 0 1 1]
 [0 0 0 0 1 0 1 1 1 0]
 [0 1 1 0 0 0 1 1 0 0]]


# 89. How to get the n largest values of an array

In [103]:
n = 5
Z = np.random.rand(10)
n_largest_result = np.sort(Z)[-n:]
print("N Largest Values:\n", n_largest_result)

N Largest Values:
 [0.50221687 0.69433801 0.71911732 0.7684228  0.99764229]


# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [104]:
arrays = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7])]
dtype = np.result_type(*arrays)
cartesian_product_result = np.stack(np.meshgrid(*arrays, indexing='ij'), axis=-1).reshape(-1, len(arrays)).astype(dtype)
print("Cartesian Product:\n", cartesian_product_result)

Cartesian Product:
 [[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


# 91. How to create a record array from a regular array?

In [105]:
record_array_result = np.array([(1, 2, 3), (4, 5, 6)], dtype=[('a', int), ('b', int), ('c', int)])
print("Record Array:\n", record_array_result)

Record Array:
 [(1, 2, 3) (4, 5, 6)]


# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [106]:
Z = np.random.rand(1000000)
power_results = (Z**3, np.power(Z, 3), Z * Z * Z)
print("Power Computation Completed")

Power Computation Completed


# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [107]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))
matching_rows_result = np.array([row for row in A if np.all(np.isin(B, row))])
print("Matching Rows:\n", matching_rows_result)

Matching Rows:
 []


# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [108]:
A = np.random.randint(0, 5, (10, 3))
unique_value_rows_result = A[np.any(A[:, None] != A[:, :, None], axis=(1, 2))]
print("Unique Value Rows:\n", unique_value_rows_result)

Unique Value Rows:
 [[2 0 4]
 [4 0 2]
 [4 2 4]
 [0 3 2]
 [3 4 3]
 [3 4 3]
 [2 4 2]
 [0 1 4]]


# 95. Convert a vector of ints into a matrix binary representation 

In [109]:
Z = np.array([0, 1, 2, 3, 4])
binary_matrix_result = ((Z[:, None] & (1 << np.arange(8))) > 0).astype(int)
print("Binary Matrix:\n", binary_matrix_result)

Binary Matrix:
 [[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]]


# 96. Given a two dimensional array, how to extract unique rows?

In [110]:
A = np.random.randint(0, 2, (10, 3))
unique_rows_result = np.unique(A, axis=0)
print("Unique Rows:\n", unique_rows_result)

Unique Rows:
 [[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [111]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
einsum_results = {
    'inner': np.einsum('i,i->', A, B),
    'outer': np.einsum('i,j->ij', A, B),
    'sum': np.einsum('i->', A),
    'elementwise': np.einsum('i,i->i', A, B)
}
print("Einsum Operations:\n", einsum_results)

Einsum Operations:
 {'inner': np.int64(32), 'outer': array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]]), 'sum': np.int64(6), 'elementwise': array([ 4, 10, 18])}


# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [112]:
X = np.linspace(0, 10, num=10)
Y = np.sin(X)
distances = np.linspace(0, 10, num=5)
indices = np.searchsorted(X, distances)
equidistant_sampling_result = Y[indices]
print("Equidistant Sampling:\n", equidistant_sampling_result)

Equidistant Sampling:
 [ 0.         -0.19056796 -0.66510151  0.99709789 -0.54402111]


# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n

In [113]:
n = 5
X = np.random.randint(0, 5, (10, 3))
select_multinomial_result = X[np.sum(X, axis=1) == n]
print("Selected Multinomial Rows:\n", select_multinomial_result)

Selected Multinomial Rows:
 [[2 0 3]
 [0 1 4]
 [1 1 3]]


# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)

In [114]:
X = np.random.randn(1000)
N = 1000
means = np.mean(np.random.choice(X, (N, len(X)), replace=True), axis=1)
bootstrap_confidence_result = np.percentile(means, [2.5, 97.5])
print("Bootstrapped 95% Confidence Interval:\n", bootstrap_confidence_result)

Bootstrapped 95% Confidence Interval:
 [-0.10079845  0.0179748 ]
